SUPABASE_URL = "https://jdhtviwxgfzrpjdotike.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkaHR2aXd4Z2Z6cnBqZG90aWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgzNjc0NTIsImV4cCI6MjEwMzk0MzQ1Mn0.P5cHjQwkNHNl6yeyKiiESJIqaK2Fk0LGP6DxCSTZ1fQ"
